# Update dependencies with Dependabot

version: 2
updates:
  # Set update schedule for Ruby Bundler
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    labels:
      - npm dependencies

  # Set update schedule for GitHub Actions 
  # https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
